# fly.toml app configuration file generated for binance-demo-cronjob-dusky-river-105 on 2026-05-10T20:07:43+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'binance-demo-cronjob-dusky-river-105'
primary_region = 'sin'

[experimental]
  auto_rollback = true

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'immediate'

[processes]
  app = 'python -m src.main --futures'

[[restart]]
  policy = 'always'
  retries = 10

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
